# -*- coding: utf-8 -*-
"""Devi Farichah.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nt9OSueQLVGoaPbdlPHqQLQCEvsVtTYV

Penyusunan Peta Tematik Derivatif Proyeksi Perubahan Tutupan Lahan
"""

# Install library yang dibutuhkan
! pip install pandas
! pip install geopandas
! pip install numpy
! pip install matplotlib
! pip install scikit-learn
! pip install scikit-image
! pip install earthpy
! pip install scipy

# Import library yang akan digunakan
import numpy as np
import pandas as pd
import geopandas as gpd
import rasterio
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, cohen_kappa_score
import matplotlib.pyplot as plt
import os

# Membaca penyimpanan drive
from google.colab import drive

drive.mount('/content/drive')

# Menentukan lokasi penyimpanan lokasi yang diinginkan
loc = '/content/drive/MyDrive/ILASPP/'

# Mengubah ke penyimpanan yang sudah didefinisikan sebelumnya
os.chdir(loc)

# Memastikan lokasi penyimpanan sudah sesuai dengan yang telah ditentukan
print('Working Directory: ',os.getcwd())

# Mengetahui informasi citra Satelit 2A 2020
with rasterio.open("Sarbagita_2020.tif") as src:
    print(src.count)   # jumlah band
    print(src.crs)      # sistem koordinat
    print(src.bounds)   # cakupan wilayah

# Mengetahui informasi citra Satelit 2A 2023
with rasterio.open("Sarbagita_2023.tif") as src:
    print(src.count)   # jumlah band
    print(src.crs)      # sistem koordinat
    print(src.bounds)   # cakupan wilayah

# Reproject citra ke sistem koordinat UTM (citra Sentinel 2A 2020)
from rasterio.warp import calculate_default_transform, reproject, Resampling

def reproject_to_utm(src_path, dst_path, dst_crs="EPSG:32750"):
    with rasterio.open(src_path) as src:
        transform, w, h = calculate_default_transform(src.crs, dst_crs, src.width, src.height, *src.bounds)
        kwargs = src.meta.copy()
        kwargs.update(crs=dst_crs, transform=transform, width=w, height=h)

        with rasterio.open(dst_path, "w", **kwargs) as dst:
            for i in range(1, src.count + 1):
                reproject(
                    source=rasterio.band(src, i),
                    destination=rasterio.band(dst, i),
                    src_transform=src.transform, src_crs=src.crs,
                    dst_transform=transform, dst_crs=dst_crs,
                    resampling=Resampling.nearest)
    print(f"Selesai reproject: {dst_path}")

reproject_to_utm("Sarbagita_2020.tif", "Sarbagita_2020_utm.tif")

# Reproject citra ke sistem koordinat UTM (citra Sentinel 2A 2023)
from rasterio.warp import calculate_default_transform, reproject, Resampling

def reproject_to_utm(src_path, dst_path, dst_crs="EPSG:32750"):
    with rasterio.open(src_path) as src:
        transform, w, h = calculate_default_transform(src.crs, dst_crs, src.width, src.height, *src.bounds)
        kwargs = src.meta.copy()
        kwargs.update(crs=dst_crs, transform=transform, width=w, height=h)

        with rasterio.open(dst_path, "w", **kwargs) as dst:
            for i in range(1, src.count + 1):
                reproject(
                    source=rasterio.band(src, i),
                    destination=rasterio.band(dst, i),
                    src_transform=src.transform, src_crs=src.crs,
                    dst_transform=transform, dst_crs=dst_crs,
                    resampling=Resampling.nearest)
    print(f"Selesai reproject: {dst_path}")

reproject_to_utm("Sarbagita_2023.tif", "Sarbagita_2023_utm.tif")

# Mengetahui informasi citra Satelit 2A
with rasterio.open("Sarbagita_2020_utm.tif") as src:
    print(src.count)   # jumlah band
    print(src.crs)      # sistem koordinat
    print(src.bounds)   # cakupan wilayah

# Mengetahui informasi citra Satelit 2A
with rasterio.open("Sarbagita_2023_utm.tif") as src:
    print(src.count)   # jumlah band
    print(src.crs)      # sistem koordinat
    print(src.bounds)   # cakupan wilayah

with rasterio.open("Sarbagita_2020_utm.tif") as src:
    img = src.read([1, 2, 3])  # Band Red, Green, Blue

# Normalisasi agar kontras terlihat jelas
img_norm = np.clip(img / img.max(), 0, 1)

plt.figure(figsize=(10, 8))
plt.imshow(np.moveaxis(img_norm, 0, -1))  # Mengubah format band ke height, width, band
plt.title("Citra Sarbagita 2020")
plt.axis("off")
plt.show()

with rasterio.open("Sarbagita_2023_utm.tif") as src:
    img = src.read([1, 2, 3])  # Band Red, Green, Blue

# Normalisasi agar kontras terlihat jelas
img_norm = np.clip(img / img.max(), 0, 1)

plt.figure(figsize=(10, 8))
plt.imshow(np.moveaxis(img_norm, 0, -1))  # Mengubah format band ke height, width, band
plt.title("Citra Sarbagita 2023")
plt.axis("off")
plt.show()

# Data training sample
print(os.path.exists("training_2020_2023.shp")) # Menggunakan data sampel yang sama karena tidak ada perubahan tutupan lahan di tahun 2020 dan 2023

# Pengecekan isi data training sample
titik_2020_2023 = gpd.read_file("training_2020_2023.shp")

print("Jumlah total titik:", len(titik_2020_2023))
print("\nJumlah titik per kelas:")
print(titik_2020_2023["class_id"].value_counts())

print("\nContoh 5 baris data:")
titik_2020_2023.head()

# Mengambil nilai piksel dari training sample 2020
nilai_band = []
label_kelas = []

with rasterio.open("Sarbagita_2020_utm.tif") as src:
    for index, baris in titik_2020_2023.iterrows():
        geom = baris.geometry
        row, col = src.index(geom.x, geom.y)
        nilai_piksel = src.read()[:, row, col]
        nilai_band.append(nilai_piksel)
        label_kelas.append(baris["class_id"])

X_2020 = np.array(nilai_band)
y_2020 = np.array(label_kelas)

print("Jumlah data latih:", len(X_2020))

# Melatih model dan membuat peta klasifikasi
X_train, X_test, y_train, y_test = train_test_split(X_2020, y_2020, test_size=0.3, random_state=42, stratify=y_2020)

model_2020 = RandomForestClassifier(n_estimators=300, random_state=42)
model_2020.fit(X_train, y_train)

print("Model 2020 selesai dilatih")

with rasterio.open("Sarbagita_2020_utm.tif") as src:
    citra = src.read()
    profile = src.profile

jumlah_band, tinggi, lebar = citra.shape
citra_flat = citra.reshape(jumlah_band, -1).T

hasil_prediksi = model_2020.predict(citra_flat)
peta_2020 = hasil_prediksi.reshape(tinggi, lebar)

profile.update(dtype=rasterio.uint8, count=1)
with rasterio.open("landcover_2020.tif", "w", **profile) as dst:
    dst.write(peta_2020.astype(rasterio.uint8), 1)

print("Peta klasifikasi 2020 selesai dan tersimpan")

# Hasil klasifiasi
plt.figure(figsize=(10, 8))
plt.imshow(peta_2020, cmap="tab10")
plt.title("Peta Klasifikasi Tutupan Lahan 2020")
plt.colorbar(label="Kelas")
plt.axis("off")
plt.show()

from matplotlib.colors import ListedColormap, BoundaryNorm

# Menentukan kelas tutupan lahan
DAFTAR_KELAS = {
    1: "Vegetasi",
    2: "Lahan Terbangun",
    3: "Pertanian",
}

warna = ["#1a9850", "#d73027", "#fee08b"]  # hijau, merah, kuning
cmap = ListedColormap(warna)
batas = [0.5, 1.5, 2.5, 3.5]  # batas antar kelas
norm = BoundaryNorm(batas, cmap.N)

plt.figure(figsize=(10, 8))
plt.imshow(peta_2020, cmap=cmap, norm=norm)
plt.title("Peta Klasifikasi Tutupan Lahan 2020")
cbar = plt.colorbar(ticks=[1, 2, 3])
cbar.ax.set_yticklabels(list(DAFTAR_KELAS.values()))
plt.axis("off")
plt.show()

"""Berdasarkan hasil klasifikasi terdapat area nodata di sekitar tepi citra hasil reprojection yang turut terklasifikasi sebagai salah satu kelas. Hal ini tidak mempengaruhi hasil uji akurasi karena training sample diambil eksklusif dari area bertutupan lahan valid"""

mask_valid_2020 = ~np.all(citra == 0, axis=0)
peta_2020_tampil = np.where(mask_valid_2020, peta_2020, np.nan)

plt.figure(figsize=(10, 8))
plt.imshow(peta_2020_tampil, cmap=cmap, norm=norm)
cbar = plt.colorbar(ticks=[1, 2, 3])
cbar.ax.set_yticklabels(list(DAFTAR_KELAS.values()))
plt.title("Peta Klasifikasi Tutupan Lahan 2020")
plt.axis("off")
plt.show()

y_pred = model_2020.predict(X_test)
label_urut = sorted(DAFTAR_KELAS.keys())

cm = confusion_matrix(y_test, y_pred, labels=label_urut)
overall_accuracy = np.trace(cm) / np.sum(cm)
kappa = cohen_kappa_score(y_test, y_pred)
producer_acc = np.diag(cm) / np.sum(cm, axis=0)
user_acc = np.diag(cm) / np.sum(cm, axis=1)

tabel_akurasi_2020 = pd.DataFrame({
    "Kelas": [DAFTAR_KELAS[k] for k in label_urut],
    "Producer_Accuracy (%)": np.round(producer_acc * 100, 2),
    "User_Accuracy (%)": np.round(user_acc * 100, 2),
})

print("Overall Accuracy:", round(overall_accuracy * 100, 2), "%")
print("Cohen's Kappa:", round(kappa, 3))
tabel_akurasi_2020.to_excel("akurasi_2020.xlsx", index=False)
tabel_akurasi_2020

# Mengambil nilai piksel pada training sample 2023
titik_2023 = gpd.read_file("training_2020_2023.shp")

nilai_band = []
label_kelas = []

with rasterio.open("Sarbagita_2023_utm.tif") as src:
    for index, baris in titik_2023.iterrows():
        geom = baris.geometry
        row, col = src.index(geom.x, geom.y)
        nilai_piksel = src.read()[:, row, col]
        nilai_band.append(nilai_piksel)
        label_kelas.append(baris["class_id"])

X_2023 = np.array(nilai_band)
y_2023 = np.array(label_kelas)

print("Jumlah data latih 2023:", len(X_2023))

# Melatih model dan membuat peta klasifikasi
X_train, X_test, y_train, y_test = train_test_split(X_2023, y_2023, test_size=0.3, random_state=42, stratify=y_2023)

model_2023 = RandomForestClassifier(n_estimators=300, random_state=42)
model_2023.fit(X_train, y_train)

with rasterio.open("Sarbagita_2023_utm.tif") as src:
    citra = src.read()
    profile = src.profile

jumlah_band, tinggi, lebar = citra.shape
citra_flat = citra.reshape(jumlah_band, -1).T
hasil_prediksi = model_2023.predict(citra_flat)
peta_2023 = hasil_prediksi.reshape(tinggi, lebar)

profile.update(dtype=rasterio.uint8, count=1)
with rasterio.open("landcover_2023.tif", "w", **profile) as dst:
    dst.write(peta_2023.astype(rasterio.uint8), 1)

print("Peta klasifikasi 2023 selesai dan tersimpan")

from matplotlib.colors import ListedColormap, BoundaryNorm

# Menentukan kelas tutupan lahan
DAFTAR_KELAS = {
    1: "Vegetasi",
    2: "Lahan Terbangun",
    3: "Pertanian",
}

warna = ["#1a9850", "#d73027", "#fee08b"]  # hijau, merah, kuning
cmap = ListedColormap(warna)
batas = [0.5, 1.5, 2.5, 3.5]  # batas antar kelas
norm = BoundaryNorm(batas, cmap.N)

plt.figure(figsize=(10, 8))
plt.imshow(peta_2023, cmap=cmap, norm=norm)
plt.title("Peta Klasifikasi Tutupan Lahan 2023")
cbar = plt.colorbar(ticks=[1, 2, 3])
cbar.ax.set_yticklabels(list(DAFTAR_KELAS.values()))
plt.axis("off")
plt.show()

mask_valid_2023 = ~np.all(citra == 0, axis=0)
peta_2023_tampil = np.where(mask_valid_2023, peta_2023, np.nan)

plt.figure(figsize=(10, 8))
plt.imshow(peta_2023_tampil, cmap=cmap, norm=norm)
cbar = plt.colorbar(ticks=[1, 2, 3])
cbar.ax.set_yticklabels(list(DAFTAR_KELAS.values()))
plt.title("Peta Klasifikasi Tutupan Lahan 2023")
plt.axis("off")
plt.show()

y_pred = model_2023.predict(X_test)
label_urut = sorted(DAFTAR_KELAS.keys())

cm = confusion_matrix(y_test, y_pred, labels=label_urut)
overall_accuracy = np.trace(cm) / np.sum(cm)
kappa = cohen_kappa_score(y_test, y_pred)
producer_acc = np.diag(cm) / np.sum(cm, axis=0)
user_acc = np.diag(cm) / np.sum(cm, axis=1)

tabel_akurasi_2023 = pd.DataFrame({
    "Kelas": [DAFTAR_KELAS[k] for k in label_urut],
    "Producer_Accuracy (%)": np.round(producer_acc * 100, 2),
    "User_Accuracy (%)": np.round(user_acc * 100, 2),
})

print("Overall Accuracy:", round(overall_accuracy * 100, 2), "%")
print("Cohen's Kappa:", round(kappa, 3))
tabel_akurasi_2023.to_excel("akurasi_2023.xlsx", index=False)
tabel_akurasi_2023

# Menghitung persentase perubahan tiap kelas dari 2020 ke 2023
label_urut = sorted(DAFTAR_KELAS.keys())
n = len(label_urut)
matriks = np.zeros((n, n))

for i, kelas_awal in enumerate(label_urut):
    for j, kelas_akhir in enumerate(label_urut):
        matriks[i, j] = np.sum((peta_2020 == kelas_awal) & (peta_2023 == kelas_akhir))

total_per_baris = matriks.sum(axis=1, keepdims=True)
total_per_baris[total_per_baris == 0] = 1
matriks_prob = matriks / total_per_baris

print("Matriks probabilitas:")
print(pd.DataFrame(matriks_prob, index=DAFTAR_KELAS.values(), columns=DAFTAR_KELAS.values()))

# Menerapkan probabilitas untuk prediksi peta tutupan lahan 2026
np.random.seed(42)
peta_2026 = peta_2023.copy()

for i, kelas in enumerate(label_urut):
    lokasi = np.where(peta_2023 == kelas)
    jumlah_piksel = len(lokasi[0])
    if jumlah_piksel == 0:
        continue
    kelas_baru = np.random.choice(label_urut, size=jumlah_piksel, p=matriks_prob[i])
    peta_2026[lokasi] = kelas_baru

# Menyimpan hasil prediksi
with rasterio.open("Sarbagita_2023_utm.tif") as src:
    profile = src.profile
profile.update(dtype=rasterio.uint8, count=1)

with rasterio.open("landcover_projection_2026.tif", "w", **profile) as dst:
    dst.write(peta_2026.astype(rasterio.uint8), 1)

print("Peta prediksi 2026 selesai dan tersimpan")

# Membuat peta prediksi tutupan lahan 2026
peta_2026_tampil = np.where(mask_valid_2023, peta_2026, np.nan)

plt.figure(figsize=(10, 8))
plt.imshow(peta_2026_tampil, cmap=cmap, norm=norm)
cbar = plt.colorbar(ticks=[1, 2, 3])
cbar.ax.set_yticklabels(list(DAFTAR_KELAS.values()))
plt.title("Peta Prediksi Tutupan Lahan 2026")
plt.axis("off")
plt.show()